name: swagger_json_to_dart
version: 0.0.1
homepage: 'https://github.com/Invincible1996'

environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  dio: any
  pretty_dio_logger: any
  common_utils: any
  logger: any
dev_dependencies:
